### ISSUE TITLE
manualでの施錠解錠メッセージが、変な時間に出て来る。

### ISSUE THREAD

**Issue by chihiroando** [cosmoway/smalo-android#5]
特に早朝が目立ちます。

**Comment by yuukis** [comment]
気持ち悪いのでなんとかしたいですねー

**Comment by gokazy** [comment]
これは、Androidのissueが正しいのかな…

**Comment by yuukis** [comment]
あ、ホントだ。

@chihiroando さん、この issue を _smalo-android_ に立てた理由はあります？
なければ、 _smalo-server_ の方が内容的にふさわしいかも

**Comment by yuukis** [comment]
@chihiroando さん、この issue は↓に移動したという理解で良いですか？

https://github.com/cosmoway/smalo-server/issues/3
